EMPTY: int

class Buffer:
    width: int
    height: int
    def __init__(self, width: int, height: int) -> None: ...
    def row_text(self, row: int) -> str: ...

def parse_line(buf: Buffer, row: int, line: str) -> None: ...
def render_full(buf: Buffer) -> str: ...
def render_diff(cur: Buffer, prev: Buffer) -> str: ...
